import datetime as dt
import math

from atmoresponse.aeronet import (
    AeronetSite,
    aeronet_providers,
    aod_at,
    candidate_sites,
    from_aeronet,
    nearest_in_time,
    parse_aod_rows,
    parse_site_list,
    query_aod_rows,
    row_datetime,
)
from atmoresponse.aod import AodQuery, AodSource, resolve_aod


SITE_TEXT = """Site_Name,Longitude(decimal_degrees),Latitude(decimal_degrees)
Example_Near,-118.0000,34.0000
Example_Far,-121.0000,36.0000
"""

AOD_TEXT = """AERONET Version 3
The following data are cloud screened
Contact PI for use
Generated by fixture
Units are unitless
Date(dd:mm:yyyy),Time(hh:mm:ss),AOD_500nm,AOD_675nm
29:08:2026,18:00:00,0.100,0.080
29:08:2026,19:00:00,0.200,0.160
"""


class Response:
    def __init__(self, text):
        self.text = text

    def raise_for_status(self):
        return None


class Session:
    def __init__(self, rows_by_site):
        self.rows_by_site = rows_by_site
        self.calls = []

    def get(self, url, params=None, timeout=None):
        self.calls.append((url, params, timeout))
        if params is None:
            return Response(SITE_TEXT)
        return Response(self.rows_by_site.get(params["site"], ""))


def test_parse_site_list_skips_non_site_rows():
    sites = parse_site_list("header,line\n" + SITE_TEXT)

    assert sites == [
        AeronetSite("Example_Near", longitude=-118.0, latitude=34.0),
        AeronetSite("Example_Far", longitude=-121.0, latitude=36.0),
    ]


def test_parse_aod_rows_finds_header_and_rows():
    rows = parse_aod_rows(AOD_TEXT)

    assert rows[0]["Date(dd:mm:yyyy)"] == "29:08:2026"
    assert rows[1]["AOD_675nm"] == "0.160"


def test_query_aod_rows_sets_aeronet_parameters():
    session = Session({"Example_Near": AOD_TEXT})

    rows = query_aod_rows(
        "Example_Near",
        dt.date(2026, 8, 29),
        dt.date(2026, 8, 29),
        session=session,
    )

    _, params, timeout = session.calls[0]
    assert rows
    assert params["site"] == "Example_Near"
    assert params["AOD15"] == 1
    assert params["AVG"] == 10
    assert params["if_no_html"] == 1
    assert timeout == 30


def test_row_datetime_and_nearest_in_time():
    rows = parse_aod_rows(AOD_TEXT)

    row, seconds = nearest_in_time(rows, dt.datetime(2026, 8, 29, 18, 20))

    assert row_datetime(row) == dt.datetime(2026, 8, 29, 18)
    assert seconds == 20 * 60


def test_aod_at_interpolates_to_550_nm():
    row = parse_aod_rows(AOD_TEXT)[0]
    expected = 0.1 * (550.0 / 500.0) ** (
        -(-math.log(0.08 / 0.1) / math.log(675.0 / 500.0))
    )

    assert aod_at(row, 550.0) == expected


def test_candidate_sites_applies_distance_window():
    sites = parse_site_list(SITE_TEXT)
    query = AodQuery(
        latitude=34.0,
        longitude=-118.0,
        when=dt.datetime(2026, 8, 29, 18),
        max_distance_km=50.0,
    )

    candidates = candidate_sites(query, sites)

    assert [site.name for site, _ in candidates] == ["Example_Near"]


def test_from_aeronet_uses_nearest_site_with_data():
    sites = [
        AeronetSite("Nearest_Empty", longitude=-118.0, latitude=34.0),
        AeronetSite("Next_With_Data", longitude=-118.1, latitude=34.0),
    ]
    session = Session({"Nearest_Empty": "", "Next_With_Data": AOD_TEXT})
    query = AodQuery(latitude=34.0, longitude=-118.0, when=dt.datetime(2026, 8, 29, 18, 10))

    estimate = from_aeronet(query, session=session, sites=sites)

    assert estimate.source is AodSource.AERONET
    assert estimate.independence == "measurement"
    assert estimate.detail == "site Next_With_Data"
    assert estimate.dt_minutes == 10


def test_from_aeronet_returns_none_when_match_is_too_stale():
    session = Session({"Example_Near": AOD_TEXT})
    query = AodQuery(
        latitude=34.0,
        longitude=-118.0,
        when=dt.datetime(2026, 8, 29, 23),
        max_dt_minutes=30.0,
    )

    assert from_aeronet(query, session=session, sites=parse_site_list(SITE_TEXT)) is None


def test_aeronet_provider_mapping_integrates_with_resolve_aod():
    session = Session({"Example_Near": AOD_TEXT})
    query = AodQuery(latitude=34.0, longitude=-118.0, when=dt.datetime(2026, 8, 29, 18))

    estimate = resolve_aod(
        query,
        providers=aeronet_providers(session=session, sites=parse_site_list(SITE_TEXT)),
    )

    assert estimate.source is AodSource.AERONET
